// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_claude/test/data/contact/repository/contact_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_claude/core/storage/common/dto/storage_response.dart'
    as _i4;
import 'package:flutter_claude/core/storage/database/drift/drift_database_service.dart'
    as _i6;
import 'package:flutter_claude/data/contact/datasource/local/contact_local_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ContactLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactLocalDataSource extends _i1.Mock
    implements _i2.ContactLocalDataSource {
  MockContactLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.StorageResponse<String>> getNameFromPrefs() =>
      (super.noSuchMethod(
            Invocation.method(#getNameFromPrefs, []),
            returnValue: _i3.Future<_i4.StorageResponse<String>>.value(
              _i5.dummyValue<_i4.StorageResponse<String>>(
                this,
                Invocation.method(#getNameFromPrefs, []),
              ),
            ),
          )
          as _i3.Future<_i4.StorageResponse<String>>);

  @override
  _i3.Future<_i4.StorageResponse<void>> setNameToPrefs(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setNameToPrefs, [value]),
            returnValue: _i3.Future<_i4.StorageResponse<void>>.value(
              _i5.dummyValue<_i4.StorageResponse<void>>(
                this,
                Invocation.method(#setNameToPrefs, [value]),
              ),
            ),
          )
          as _i3.Future<_i4.StorageResponse<void>>);

  @override
  _i3.Future<_i4.StorageResponse<String>> getPhoneFromPrefs() =>
      (super.noSuchMethod(
            Invocation.method(#getPhoneFromPrefs, []),
            returnValue: _i3.Future<_i4.StorageResponse<String>>.value(
              _i5.dummyValue<_i4.StorageResponse<String>>(
                this,
                Invocation.method(#getPhoneFromPrefs, []),
              ),
            ),
          )
          as _i3.Future<_i4.StorageResponse<String>>);

  @override
  _i3.Future<_i4.StorageResponse<void>> setPhoneToPrefs(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setPhoneToPrefs, [value]),
            returnValue: _i3.Future<_i4.StorageResponse<void>>.value(
              _i5.dummyValue<_i4.StorageResponse<void>>(
                this,
                Invocation.method(#setPhoneToPrefs, [value]),
              ),
            ),
          )
          as _i3.Future<_i4.StorageResponse<void>>);

  @override
  _i3.Future<_i4.StorageResponse<String>> readNameFromSecure() =>
      (super.noSuchMethod(
            Invocation.method(#readNameFromSecure, []),
            returnValue: _i3.Future<_i4.StorageResponse<String>>.value(
              _i5.dummyValue<_i4.StorageResponse<String>>(
                this,
                Invocation.method(#readNameFromSecure, []),
              ),
            ),
          )
          as _i3.Future<_i4.StorageResponse<String>>);

  @override
  _i3.Future<_i4.StorageResponse<void>> writeNameToSecure(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#writeNameToSecure, [value]),
            returnValue: _i3.Future<_i4.StorageResponse<void>>.value(
              _i5.dummyValue<_i4.StorageResponse<void>>(
                this,
                Invocation.method(#writeNameToSecure, [value]),
              ),
            ),
          )
          as _i3.Future<_i4.StorageResponse<void>>);

  @override
  _i3.Future<_i4.StorageResponse<String>> readPhoneFromSecure() =>
      (super.noSuchMethod(
            Invocation.method(#readPhoneFromSecure, []),
            returnValue: _i3.Future<_i4.StorageResponse<String>>.value(
              _i5.dummyValue<_i4.StorageResponse<String>>(
                this,
                Invocation.method(#readPhoneFromSecure, []),
              ),
            ),
          )
          as _i3.Future<_i4.StorageResponse<String>>);

  @override
  _i3.Future<_i4.StorageResponse<void>> writePhoneToSecure(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#writePhoneToSecure, [value]),
            returnValue: _i3.Future<_i4.StorageResponse<void>>.value(
              _i5.dummyValue<_i4.StorageResponse<void>>(
                this,
                Invocation.method(#writePhoneToSecure, [value]),
              ),
            ),
          )
          as _i3.Future<_i4.StorageResponse<void>>);

  @override
  _i3.Future<_i4.StorageResponse<List<_i6.ContactTableData>>>
  getAllContacts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllContacts, []),
            returnValue:
                _i3.Future<
                  _i4.StorageResponse<List<_i6.ContactTableData>>
                >.value(
                  _i5.dummyValue<
                    _i4.StorageResponse<List<_i6.ContactTableData>>
                  >(this, Invocation.method(#getAllContacts, [])),
                ),
          )
          as _i3.Future<_i4.StorageResponse<List<_i6.ContactTableData>>>);

  @override
  _i3.Future<_i4.StorageResponse<void>> insertContact({
    required _i6.ContactTableCompanion? companion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertContact, [], {#companion: companion}),
            returnValue: _i3.Future<_i4.StorageResponse<void>>.value(
              _i5.dummyValue<_i4.StorageResponse<void>>(
                this,
                Invocation.method(#insertContact, [], {#companion: companion}),
              ),
            ),
          )
          as _i3.Future<_i4.StorageResponse<void>>);

  @override
  _i3.Future<_i4.StorageResponse<void>> deleteContact({required int? id}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteContact, [], {#id: id}),
            returnValue: _i3.Future<_i4.StorageResponse<void>>.value(
              _i5.dummyValue<_i4.StorageResponse<void>>(
                this,
                Invocation.method(#deleteContact, [], {#id: id}),
              ),
            ),
          )
          as _i3.Future<_i4.StorageResponse<void>>);
}
