// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_claude/test/domain/contact/usecase/load_contact_from_secure_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_claude/domain/common/entity/app_result.dart' as _i4;
import 'package:flutter_claude/domain/contact/entity/contact_entity.dart'
    as _i5;
import 'package:flutter_claude/domain/contact/repository/contact_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ContactRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactRepository extends _i1.Mock implements _i2.ContactRepository {
  MockContactRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.AppResult<_i5.ContactEntity?>> readContactFromPrefs() =>
      (super.noSuchMethod(
            Invocation.method(#readContactFromPrefs, []),
            returnValue: _i3.Future<_i4.AppResult<_i5.ContactEntity?>>.value(
              _i6.dummyValue<_i4.AppResult<_i5.ContactEntity?>>(
                this,
                Invocation.method(#readContactFromPrefs, []),
              ),
            ),
          )
          as _i3.Future<_i4.AppResult<_i5.ContactEntity?>>);

  @override
  _i3.Future<_i4.AppResult<void>> writeContactToPrefs(
    _i5.ContactEntity? entity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeContactToPrefs, [entity]),
            returnValue: _i3.Future<_i4.AppResult<void>>.value(
              _i6.dummyValue<_i4.AppResult<void>>(
                this,
                Invocation.method(#writeContactToPrefs, [entity]),
              ),
            ),
          )
          as _i3.Future<_i4.AppResult<void>>);

  @override
  _i3.Future<_i4.AppResult<_i5.ContactEntity?>> readContactFromSecure() =>
      (super.noSuchMethod(
            Invocation.method(#readContactFromSecure, []),
            returnValue: _i3.Future<_i4.AppResult<_i5.ContactEntity?>>.value(
              _i6.dummyValue<_i4.AppResult<_i5.ContactEntity?>>(
                this,
                Invocation.method(#readContactFromSecure, []),
              ),
            ),
          )
          as _i3.Future<_i4.AppResult<_i5.ContactEntity?>>);

  @override
  _i3.Future<_i4.AppResult<void>> writeContactToSecure(
    _i5.ContactEntity? entity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeContactToSecure, [entity]),
            returnValue: _i3.Future<_i4.AppResult<void>>.value(
              _i6.dummyValue<_i4.AppResult<void>>(
                this,
                Invocation.method(#writeContactToSecure, [entity]),
              ),
            ),
          )
          as _i3.Future<_i4.AppResult<void>>);

  @override
  _i3.Future<_i4.AppResult<List<_i5.ContactEntity>>> getAllContacts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllContacts, []),
            returnValue:
                _i3.Future<_i4.AppResult<List<_i5.ContactEntity>>>.value(
                  _i6.dummyValue<_i4.AppResult<List<_i5.ContactEntity>>>(
                    this,
                    Invocation.method(#getAllContacts, []),
                  ),
                ),
          )
          as _i3.Future<_i4.AppResult<List<_i5.ContactEntity>>>);

  @override
  _i3.Future<_i4.AppResult<void>> insertContact(_i5.ContactEntity? entity) =>
      (super.noSuchMethod(
            Invocation.method(#insertContact, [entity]),
            returnValue: _i3.Future<_i4.AppResult<void>>.value(
              _i6.dummyValue<_i4.AppResult<void>>(
                this,
                Invocation.method(#insertContact, [entity]),
              ),
            ),
          )
          as _i3.Future<_i4.AppResult<void>>);

  @override
  _i3.Future<_i4.AppResult<void>> deleteContact({required int? id}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteContact, [], {#id: id}),
            returnValue: _i3.Future<_i4.AppResult<void>>.value(
              _i6.dummyValue<_i4.AppResult<void>>(
                this,
                Invocation.method(#deleteContact, [], {#id: id}),
              ),
            ),
          )
          as _i3.Future<_i4.AppResult<void>>);
}
