// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_claude/test/data/post/repository/post_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_claude/core/network/http/dto/api_response.dart' as _i4;
import 'package:flutter_claude/data/post/datasource/remote/post_remote_data_source.dart'
    as _i2;
import 'package:flutter_claude/data/post/dto/request/post_request_dto.dart'
    as _i6;
import 'package:flutter_claude/data/post/dto/response/post_response_dto.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PostRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRemoteDataSource extends _i1.Mock
    implements _i2.PostRemoteDataSource {
  MockPostRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResponse<_i5.PostResponseDto>> createPost({
    required _i6.PostRequestDto? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {#request: request}),
            returnValue: _i3.Future<_i4.ApiResponse<_i5.PostResponseDto>>.value(
              _i7.dummyValue<_i4.ApiResponse<_i5.PostResponseDto>>(
                this,
                Invocation.method(#createPost, [], {#request: request}),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResponse<_i5.PostResponseDto>>);
}
